const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE'
export const REMOVE_ITEM = 'REMOVE_ITEM';
const QUANTITY_CHANGE = 'QUANTITY_CHANGE';

export const ADD_SHIPPING = 'ADD_SHIPPING';
const PRODUCT_FETCHING='PRODUCT_FETCHING';
const PRODUCT_FETCH_SUCCESS='PRODUCT_FETCHING_SUCCESS';
const PRODUCT_FETCH_FAILURE='PRODUCT_FETCHING_FAILURE';
const PRODUCT_SAVE_REQUEST="PRODUCT_SAVE_REQUEST";
const PRODUCT_SAVE_SUCCESS="PRODUCT_SAVE_SUCCESS";
const PRODUCT_SAVE_FAIL = "PRODUCT_SAVE_FAIL";
const PRODUCT_DETAILS_REQUEST= "PRODUCT_DETAILS_REQUEST";
const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
const SEARCH_QUERY_TYPING = "SEARCH_QUERY_TYPING";
const SEARCH_QUERY_DONE = "SEARCH_QUERY_DONE";


export {PRODUCT_FETCHING,PRODUCT_FETCH_SUCCESS,PRODUCT_FETCH_FAILURE,
    PRODUCT_SAVE_REQUEST,PRODUCT_SAVE_SUCCESS,PRODUCT_SAVE_FAIL,
    PRODUCT_DETAILS_REQUEST,PRODUCT_DETAILS_SUCCESS,PRODUCT_DETAILS_FAIL,
    SEARCH_QUERY_TYPING,SEARCH_QUERY_DONE,
    ADD_TO_CART_REQUEST,ADD_TO_CART_SUCCESS,ADD_TO_CART_FAILURE,
    QUANTITY_CHANGE};