export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const SUB_QUANTITY = 'SUB_QUANTITY';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const ADD_SHIPPING = 'ADD_SHIPPING';
const PRODUCT_FETCHING='PRODUCT_FETCHING';
const PRODUCT_FETCH_SUCCESS='PRODUCT_FETCHING_SUCCESS';
const PRODUCT_FETCH_FAILURE='PRODUCT_FETCHING_FAILURE';
const PRODUCT_SAVE_REQUEST="PRODUCT_SAVE_REQUEST";
const PRODUCT_SAVE_SUCCESS="PRODUCT_SAVE_SUCCESS";
const PRODUCT_SAVE_FAIL = "PRODUCT_SAVE_FAIL";

export {PRODUCT_FETCHING,PRODUCT_FETCH_SUCCESS,PRODUCT_FETCH_FAILURE,PRODUCT_SAVE_REQUEST,PRODUCT_SAVE_SUCCESS,PRODUCT_SAVE_FAIL};